---
- name: Run Python script on z/OS without gathering facts
  hosts: ibmz_servers
  gather_facts: no  # Disable gathering facts
  tasks:
    - name: Ensure the directory exists
      ansible.builtin.file:
        path: /z/z58582/sys-dash2/  # The remote path where you want to create the directory
        state: directory  

    - name: Copy the script to the remote system
      ansible.builtin.copy:
        src: ./main.py  # Path to the script on the local system
        dest: /z/z58582/sys-dash2/main.py  # Path on the remote system
        mode: '0755'

    - name: Copy requirements file to the remote system
      ansible.builtin.copy:
        src: ./requirements.txt  # Path to the script on the local system
        dest: /z/z58582/sys-dash2/requirements.txt  # Path on the remote system

    - name: Install required Python modules in virtual environment
      ansible.builtin.pip:
        requirements: /z/z58582/sys-dash2/requirements.txt
        virtualenv: /z/z58582/sys-dash2/venv
        virtualenv_command: /usr/lpp/IBM/cyp/v3r9/pyz/bin/python3 -m venv --system-site-packages

    - name: Activate virtual environment and run the script
      ansible.builtin.shell: source ./venv/bin/activate
      args:
        chdir: /z/z58582/sys-dash2
      register: result

    - name: Display the output of the previous command
      ansible.builtin.debug:
        msg: "The output was: {{ result.stdout }}"